### ISSUE TITLE
MC API changed no longer getting MC.

### ISSUE THREAD

**Issue by ericsche** [ericsche/MCinTeams#3]
Work in Progress to fix

**Comment by ericsche** [comment]
Fixed finished with a new version of the solution, simpler to install.
looking for someone to test it.

**Comment by Ancel-1** [comment]
Hi Eric! How are you ! 
Thanks for this solution ! I'll tried to fix it myself, but I will blocked on JSON format.
Where can I found the new version for test it !

**Comment by ericsche** [comment]
Doing good thanks,
Actually I have the updated version on my side but looking for someone to test it before publishing.
It is a major revemp as it is a PowerPlatform solution (easier to import) with a flow to create the SPO lists 😊



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by Ancel-1** [comment]
If you're looking for someone to test I want to be that person.
I strongly use the first version you gave me and I admit that a new one would be great :)

**Comment by ericsche** [comment]
Cool !
Lets make that happen.
Let me send you a private message so we can secure some time.
Might not be next Week but the Week after.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by ericsche** [comment]
Can't find how to send a private message do you mind sending me and email to ericsche [at] microsoft.com ?

**Comment by Ancel-1** [comment]
Hi you know already 😉 [at]SNCF
But I will send you an email.

**Comment by Ancel-1** [comment]
Hi Eric, 
Did you receive my emails to test your application?

**Comment by ericsche** [comment]
Closing issue this is fixed by version 2.
